### PR TITLE
Finish repository transfer

### PR DESCRIPTION
**Pull request by felixvisee**
This includes the following changes:
- update the product bundle identifier (`de.rheinfabrik.Dobby` to `com.trivago.Dobby`);
- update the organization name (`B264 GmbH` to `trivago GmbH`);
- update the copyright holder (`B264 GmbH` to `trivago GmbH`); and
- update the pod spec (Author?, Social Media URL?, Homepage, Git Repository URL)

as discussed in #31.

@tibr please verify all the changes are correct after the remaining fields of the pod spec have been updated accordingly.

### CODE REVIEW

**Comment by SusannProszak** [comment]
we have to clarify author and social media url with @andygrunwald who is currently on vacation. besides that thanks for the pr 👍 .

**Comment by andygrunwald** [comment]
Will Be back at the Weekend / starting next week. But feel free to drop me
a mail or a comment here with all information you need.

Am Montag, 12. September 2016 schrieb Susann Proszak :

**Comment by bckr** [comment]
To reinvigorate the discussion here: 

Hey @andygrunwald! This is the information that we need to complete the repository transfer:

**author:** This one is currently `'Rheinfabrik' => 'hi@rheinfabrik.de'`. We could stick with the company name. Then we would need a fitting trivago mail to place here. I think I would also be fine to just use one of our personal addresses if a trivago one does not exist or would be hard to maintain.

**social_media_url:** I would guess we put `https://twitter.com/trivago_tech` in here?

Thanks for your help!

**Comment by andygrunwald** [comment]
Sorry @felixjendrusch 
I was on a trip again. I talked with @SusannProszak in between and we created `opensource@trivago.com`. Hope this works :)

Thanks for your effort.

**Pull request merged**
