### PR TITLE
Verify sequences instead of collections

### PR DESCRIPTION
**Pull request by felixvisee**
Switch verification from `CollectionType` to `SequenceType`.

### CODE REVIEW

**Comment by tibr** [comment]
What's the advantage for the user?

**Comment by felixvisee** [comment]
`SequenceType` is more general than `CollectionType`.

**Comment by tibr** [comment]
Yeah but is there a concrete use case that we might want to reflect in the documentation?

**Comment by felixvisee** [comment]
It's really just about accepting a more general value.

**Pull request merged**
